"""Lesson step domain model for structured learning paths.

Lesson steps are concrete, ordered steps tied to specific sources, typed by
action (watch / read / quiz / discuss / podcast), generated by AI from the
notebook's sources, and editable by the admin.

Fields:
    ai_instructions: AI-teacher-facing guidance for this step
    artifact_id: Linked artifact (quiz/podcast) once created
    command_id: Background job ID for async podcast generation
"""

from typing import ClassVar, Literal, Optional

from loguru import logger
from pydantic import field_validator

from open_notebook.database.repository import ensure_record_id, repo_query, repo_update
from open_notebook.domain.base import ObjectModel
from open_notebook.exceptions import DatabaseOperationError, InvalidInputError


class LessonStep(ObjectModel):
    """A concrete step in a lesson plan for a notebook.

    Attributes:
        notebook_id: Reference to notebook (module) this step belongs to
        title: Human-readable title of the step
        step_type: Type of action required (watch|read|quiz|discuss)
        source_id: Optional reference to a specific source for this step
        discussion_prompt: Optional prompt for discussion-type steps
        order: Display order for drag-and-drop reordering (0-indexed)
        required: Whether this step is mandatory for the learner
        auto_generated: True if AI-generated, False if manually created by admin
    """

    table_name: ClassVar[str] = "lesson_step"
    record_id_fields: ClassVar[set[str]] = {"notebook_id", "source_id"}
    nullable_fields: ClassVar[set[str]] = {
        "source_id", "discussion_prompt", "ai_instructions",
        "artifact_id", "command_id",
        "podcast_topic", "source_ids",
    }

    notebook_id: str
    title: str
    step_type: Literal["watch", "read", "quiz", "discuss", "podcast"]
    source_id: Optional[str] = None
    source_ids: Optional[list[str]] = None   # Sources to use for this podcast (plural)
    podcast_topic: Optional[str] = None      # Topic/briefing for podcast generator
    discussion_prompt: Optional[str] = None
    ai_instructions: Optional[str] = None   # AI-teacher-facing guidance for this step
    artifact_id: Optional[str] = None       # Linked artifact (quiz/podcast) once created
    command_id: Optional[str] = None        # Background job ID for async podcast generation
    order: int = 0
    required: bool = True
    auto_generated: bool = True

    @field_validator("notebook_id")
    @classmethod
    def ensure_notebook_id_format(cls, v: str) -> str:
        """Ensure notebook_id is in RecordID format (notebook:id)."""
        if not v.startswith("notebook:"):
            return f"notebook:{v}"
        return v

    @field_validator("source_id")
    @classmethod
    def ensure_source_id_format(cls, v: Optional[str]) -> Optional[str]:
        """Ensure source_id is in RecordID format (source:id) if provided."""
        if v is None:
            return None
        if not v.startswith("source:"):
            return f"source:{v}"
        return v

    @field_validator("title")
    @classmethod
    def validate_title(cls, v: str) -> str:
        """Ensure title is not empty."""
        if not v or not v.strip():
            raise InvalidInputError("Lesson step title cannot be empty")
        return v.strip()

    def needs_embedding(self) -> bool:
        """Lesson steps are not searchable."""
        return False

    @classmethod
    async def get_for_notebook(
        cls, notebook_id: str, ordered: bool = True
    ) -> list["LessonStep"]:
        """Get all lesson steps for a notebook, optionally ordered.

        Args:
            notebook_id: Notebook record ID (with or without 'notebook:' prefix)
            ordered: If True, sort by order ASC (default), else unordered

        Returns:
            List of LessonStep instances
        """
        if not notebook_id.startswith("notebook:"):
            notebook_id = f"notebook:{notebook_id}"

        try:
            query = "SELECT * FROM lesson_step WHERE notebook_id = $notebook_id"
            if ordered:
                query += " ORDER BY order ASC"

            result = await repo_query(
                query, {"notebook_id": ensure_record_id(notebook_id)}
            )
            return [cls(**item) for item in result]
        except Exception as e:
            logger.error(
                f"Error fetching lesson steps for notebook {notebook_id}: {str(e)}"
            )
            raise DatabaseOperationError(e)

    @classmethod
    async def reorder_steps(cls, step_updates: list[dict]) -> bool:
        """Bulk update order field for multiple lesson steps.

        Args:
            step_updates: List of dicts with 'id' and 'order' keys

        Returns:
            True if successful
        """
        logger.info(f"Reordering {len(step_updates)} lesson steps")
        try:
            for item in step_updates:
                await repo_update(
                    "lesson_step",
                    item["id"],
                    {"order": item["order"]},
                )
            logger.info(f"Successfully reordered {len(step_updates)} lesson steps")
            return True
        except Exception as e:
            logger.error(f"Error reordering lesson steps: {str(e)}")
            raise DatabaseOperationError(e)

    @classmethod
    async def delete_by_id(cls, step_id: str) -> bool:
        """Delete a lesson step by ID.

        Args:
            step_id: Step record ID

        Returns:
            True if deleted successfully
        """
        try:
            await repo_query("DELETE $id", {"id": ensure_record_id(step_id)})
            logger.info(f"Deleted lesson step {step_id}")
            return True
        except Exception as e:
            logger.error(f"Error deleting lesson step {step_id}: {str(e)}")
            raise DatabaseOperationError(e)

    @classmethod
    async def delete_all_for_notebook(cls, notebook_id: str) -> int:
        """Delete ALL lesson steps (auto-generated and manual)."""
        if not notebook_id.startswith("notebook:"):
            notebook_id = f"notebook:{notebook_id}"
        result = await repo_query(
            "DELETE lesson_step WHERE notebook_id = $notebook_id RETURN BEFORE",
            {"notebook_id": ensure_record_id(notebook_id)},
        )
        return len(result) if result else 0

    @classmethod
    async def delete_auto_generated_for_notebook(cls, notebook_id: str) -> int:
        """Delete all auto-generated steps for a notebook.

        Used before re-generating the lesson plan.

        Args:
            notebook_id: Notebook record ID

        Returns:
            Number of deleted steps
        """
        if not notebook_id.startswith("notebook:"):
            notebook_id = f"notebook:{notebook_id}"

        try:
            result = await repo_query(
                "DELETE lesson_step WHERE notebook_id = $notebook_id AND auto_generated = true RETURN BEFORE",
                {"notebook_id": ensure_record_id(notebook_id)},
            )
            count = len(result) if result else 0
            logger.info(
                f"Deleted {count} auto-generated lesson steps for notebook {notebook_id}"
            )
            return count
        except Exception as e:
            logger.error(
                f"Error deleting auto-generated steps for notebook {notebook_id}: {str(e)}"
            )
            raise DatabaseOperationError(e)
